/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hos_system;

import db_connection.db;
import static hos_system.Hos_System.isInt;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author kobi.ktk
 */
public class Add_Staff extends javax.swing.JFrame {
    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    public Add_Staff() throws SQLException{
        initComponents();
        con=db.connect();
        tableload();
        
    }
    
    
    public void tableload()
    {
       //jTable1.setVisible(false);
       
       String x =jComboBox3.getSelectedItem().toString();
       if (x=="Nurses"){
           
           try{
           
            
            String sql="SELECT* FROM Nurses_det ";
            pst=con.prepareCall(sql);
            rs=pst.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            //Logger.getLogger(Add_doc.class.getName()).log(Level.SEVERE, null, ex);
            }
       }
       else if(x=="Maintenance staff"){
           try{
            String sql="SELECT* FROM MaintenanceStaff_det ";
            pst=con.prepareCall(sql);
            rs=pst.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        } catch (Exception e) {
            //Logger.getLogger(Add_doc.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       else if(x=="Lab assistants"){
           try{
            String sql="SELECT* FROM LabAssistants_det ";
            pst=con.prepareCall(sql);
            rs=pst.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        } catch (Exception e) {
            //Logger.getLogger(Add_doc.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
        else if(x=="Register"){
                
                
           try{
            String sql="SELECT* FROM Register_det ";
            pst=con.prepareCall(sql);
            rs=pst.executeQuery();
            
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        } catch (Exception e) {
            //Logger.getLogger(Add_doc.class.getName()).log(Level.SEVERE, null, ex);
        }
       
                }
       }
      
   
    public void  reset(){
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jComboBox1.setSelectedIndex(-1);
        jComboBox2.setSelectedIndex(-1);
        jPasswordField1.setText("");
        jPasswordField2.setText("");
        jLabel8.setText("");
    }


    
    /**
     * Creates new form Add_Staff
     * @throws java.sql.SQLException
     */

    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Add Staff");

        jLabel2.setText("Name");

        jLabel3.setText("Age");

        jLabel4.setText("City");

        jLabel5.setText("Phone No");

        jLabel6.setText("Staff Type");

        jLabel7.setText("ID");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setText("Add");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Gender");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ", "Male", "Female", "Other" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Nurses", "Maintenance staff", "Lab assistants", "Register" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox2PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jComboBox2MouseReleased(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jComboBox2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox2PropertyChange(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel10.setText("User Name");

        jLabel11.setText("Password");

        jTextField5.setEnabled(false);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jPasswordField1.setEnabled(false);

        jLabel12.setText("Re-Password");

        jPasswordField2.setEnabled(false);

        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Update");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("New Entry");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel14.setText("Staff Type");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Nurses", "Maintenance staff", "Lab assistants", "Register" }));
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });
        jComboBox3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox3PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jComboBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jComboBox3MouseReleased(evt);
            }
        });
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jComboBox3.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox3PropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                        .addComponent(jTextField5)
                                        .addComponent(jPasswordField2))
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel7))
                                        .addGap(122, 122, 122)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 101, Short.MAX_VALUE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(34, 34, 34)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(149, 149, 149))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButton6)
                        .addGap(31, 31, 31)
                        .addComponent(jButton1)
                        .addGap(48, 48, 48)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton3))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel9))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton5)))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jButton4)))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel12)
                                .addContainerGap(208, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1)
                                    .addComponent(jButton6)
                                    .addComponent(jButton2))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Name=jTextField1.getText();
        String Age =jTextField2.getText();
        String Gender=jComboBox1.getSelectedItem().toString();
        String City=jTextField3.getText();
        String Phone =jTextField4.getText();
        String Staff=jComboBox2.getSelectedItem().toString();
        String userN=jTextField5.getText();
        String Pass=jPasswordField1.getText();
        String Pass2=jPasswordField2.getText();
        
        if (("".equals(Name))||(Age=="")||(Gender=="Select")||(City=="")||(Phone=="")||(Staff=="Select")){
            JOptionPane.showMessageDialog(null, "Fill all details");
         
        }
        else if (!isInt(Phone)){
            JOptionPane.showMessageDialog(null, "Phone is invaild ");
        }
        else if ((Staff=="Register")){
            
            if(Pass2.equals(Pass)) {            
                try{
                    String sql="INSERT INTO Register_det(Name,Age,Gender,City,Phone_No,User_Name,Password) VALUES('"+Name+"','"+Age+"','"+Gender+"','"+City+"','"+Phone+"','"+userN+"','"+Pass+"')";

                    pst=con.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Successfully added");
                    reset();
                    
                }catch (Exception e){
                    JOptionPane.showMessageDialog(null,e);
                }
            } else JOptionPane.showMessageDialog(null,"Both Password are not match,Check it");
            
        }
        else if((Staff=="Lab assistants")){
            
            if(Pass2.equals(Pass)){
                
                
            
            
                try{
                    String sql="INSERT INTO LabAssistants_det(Name,Age,Gender,City,Phone_No,User_Name,Password) VALUES('"+Name+"','"+Age+"','"+Gender+"','"+City+"','"+Phone+"','"+userN+"','"+Pass+"')";

                    pst=con.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Successfully added");
                    reset();
                    
                }catch (Exception e){
                    JOptionPane.showMessageDialog(null,e);
                    
                }
            }
            
            else
                JOptionPane.showMessageDialog(null,"Both Password are not match,Check it");
            
        }
        
        else if(Staff=="Maintenance staff"){
            
             
                
                
            
            
                try{
                    String sql="INSERT INTO MaintenanceStaff_det(Name,Age,Gender,City,Phone_No) VALUES('"+Name+"','"+Age+"','"+Gender+"','"+City+"','"+Phone+"')";

                    pst=con.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Successfully added");
                    reset();
                }catch (Exception e){
                    JOptionPane.showMessageDialog(null,e);
                    
                }
            
            
            
        }
        else if(Staff=="Nurses"){
            
            
                
                
            
            
                try{
                    String sql="INSERT INTO Nurses_det(Name,Age,Gender,City,Phone_No) VALUES('"+Name+"','"+Age+"','"+Gender+"','"+City+"','"+Phone+"')";

                    pst=con.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Successfully added");
                    reset();
                }catch (Exception e){
                    JOptionPane.showMessageDialog(null,e);
                    
                }
            
            
            
        }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboBox2MouseReleased

    private void jComboBox2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox2PropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox2PropertyChange

    private void jComboBox2PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox2PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String Staff=jComboBox2.getSelectedItem().toString();
        if ((Staff=="Register")||(Staff=="Lab assistants")){
            jTextField5.setEnabled(true);
            jPasswordField1.setEnabled(true);
            jPasswordField2.setEnabled(true);
        }
        else if ((Staff!="Register")||(Staff!="Lab assistants")){
            jTextField5.setEnabled(false);
            jPasswordField1.setEnabled(false);
            jPasswordField2.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBox2PopupMenuWillBecomeInvisible

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jButton5.setEnabled(true);
        jButton4.setEnabled(true);
        jTable1.setVisible(true);
        tableload();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int x=JOptionPane.showConfirmDialog(null,"Do you really want to update?");
        if (x==0){
            
            String Name=jTextField1.getText();
        String Age =jTextField2.getText();
        String Gender=jComboBox1.getSelectedItem().toString();
        String City=jTextField3.getText();
        String Phone =jTextField4.getText();
        String Staff=jComboBox2.getSelectedItem().toString();
        String userN=jTextField5.getText();
        String Pass=jPasswordField1.getText();
        String Pass2=jPasswordField2.getText();
        String id=jLabel8.getText();
        
        if (("".equals(Name))||(Age=="")||(Gender=="Select")||(City=="")||(Phone=="")||(Staff=="Select")){
            JOptionPane.showMessageDialog(null, "Fill all details");
         
        }
        else if (!isInt(Phone)){
            JOptionPane.showMessageDialog(null, "Phone is invaild ");
        }
        else if ((Staff=="Register")){
            
            if(Pass2.equals(Pass)) {            
                try{
                    String sql="UPDATE Register_det SET Name='"+Name+"',Age='"+Age+"',Gender='"+Gender+"',City='"+City+"',Phone_No='"+Phone+"',User_Name='"+userN+"',Password='"+md5(Pass)+"' WHERE Reg_Id='"+id+"'";

                    pst=con.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Successfully added");
                    reset();
                    
                }catch (Exception e){
                    JOptionPane.showMessageDialog(null,e);
                }
            } else JOptionPane.showMessageDialog(null,"Both Password are not match,Check it");
            
        }
        else if((Staff=="Lab assistants")){
            
            if(Pass2.equals(Pass)){
                
                
            
            
                try{
                    String sql="UPDATE LabAssistants_det SET Name='"+Name+"',Age='"+Age+"',Gender='"+Gender+"',City='"+City+"',Phone_No='"+Phone+"',User_Name='"+userN+"',Password='"+Pass+"' WHERE Ass_Id='"+id+"'";


                    pst=con.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Successfully added");
                    reset();
                    
                }catch (Exception e){
                    JOptionPane.showMessageDialog(null,e);
                    
                }
            }
            
            else
                JOptionPane.showMessageDialog(null,"Both Password are not match,Check it");
            
        }
        
        else if(Staff=="Maintenance staff"){
            
             
                
                
            
            
                try{
                    String sql="UPDATE MaintenanceStaff_det SET Name='"+Name+"',Age='"+Age+"',Gender='"+Gender+"',City='"+City+"',Phone_No='"+Phone+"' WHERE Staff_id='"+id+"'";

                    

                    pst=con.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Successfully added");
                    reset();
                }catch (Exception e){
                    JOptionPane.showMessageDialog(null,e);
                    
                }
            
            
            
        }
        else if(Staff=="Nurses"){
            
            
                
                
            
            
                try{
                    
                    String sql="UPDATE Nurses_det SET Name='"+Name+"',Age='"+Age+"',Gender='"+Gender+"',City='"+City+"',Phone_No='"+Phone+"' WHERE Nur_id='"+id+"'";


                    pst=con.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Successfully added");
                    reset();
                }catch (Exception e){
                    JOptionPane.showMessageDialog(null,e);
                    
                }
            
            
        }   
            
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        String x=jComboBox3.getSelectedItem().toString();
        if(x=="Nurses"){
            int r =jTable1.getSelectedRow();
        String id=jTable1.getValueAt(r,0).toString();
        String Name=jTable1.getValueAt(r,1).toString();
        String Age=jTable1.getValueAt(r,2).toString();
        String Gender=jTable1.getValueAt(r,3).toString();
        String City=jTable1.getValueAt(r,4).toString();
        String Phone=jTable1.getValueAt(r,5).toString();
        String staff=jComboBox3.getSelectedItem().toString();
        
        
        jLabel8.setText(id);
        jComboBox1.setSelectedItem(Gender);
        jTextField4.setText(Phone);
        jTextField3.setText(City);
        jTextField2.setText(Age);
        jTextField1.setText(Name);
        jComboBox2.setSelectedItem(staff);
        }
        else if(x=="Maintenance staff"){
             int r =jTable1.getSelectedRow();
        String id=jTable1.getValueAt(r,0).toString();
        String Name=jTable1.getValueAt(r,1).toString();
        String Age=jTable1.getValueAt(r,2).toString();
        String Gender=jTable1.getValueAt(r,3).toString();
        String City=jTable1.getValueAt(r,4).toString();
        String Phone=jTable1.getValueAt(r,5).toString();
        String staff=jComboBox3.getSelectedItem().toString();
        
        jLabel8.setText(id);
        jComboBox1.setSelectedItem(Gender);
        jTextField4.setText(Phone);
        jTextField3.setText(City);
        jTextField2.setText(Age);
        jTextField1.setText(Name);
        jComboBox2.setSelectedItem(staff);
        }
        else if(x=="Lab assistants"){
             int r =jTable1.getSelectedRow();
        String id=jTable1.getValueAt(r,0).toString();
        String Name=jTable1.getValueAt(r,1).toString();
        String Age=jTable1.getValueAt(r,2).toString();
        String Gender=jTable1.getValueAt(r,3).toString();
        String City=jTable1.getValueAt(r,4).toString();
        String Phone=jTable1.getValueAt(r,5).toString();
        String userN=jTable1.getValueAt(r, 6).toString();
        String Pass=jTable1.getValueAt(r,7).toString();
        String staff=jComboBox3.getSelectedItem().toString();
        
        jLabel8.setText(id);
        jComboBox1.setSelectedItem(Gender);
        jTextField4.setText(Phone);
        jTextField3.setText(City);
        jTextField2.setText(Age);
        jTextField1.setText(Name);
        jPasswordField1.setText(Pass);
        jPasswordField2.setText(Pass);
      
        jTextField5.setText(userN);
        jComboBox2.setSelectedItem(staff);
        }
        else if(x=="Register"){
             int r =jTable1.getSelectedRow();
        String id=jTable1.getValueAt(r,0).toString();
        String Name=jTable1.getValueAt(r,1).toString();
        String Age=jTable1.getValueAt(r,2).toString();
        String Gender=jTable1.getValueAt(r,3).toString();
        String City=jTable1.getValueAt(r,4).toString();
        String Phone=jTable1.getValueAt(r,5).toString();
        String userN=jTable1.getValueAt(r, 6).toString();
        String Pass=jTable1.getValueAt(r,7).toString();
        String staff=jComboBox3.getSelectedItem().toString();
        
        
        jLabel8.setText(id);
        jComboBox1.setSelectedItem(Gender);
        jTextField4.setText(Phone);
        jTextField3.setText(City);
        jTextField2.setText(Age);
        jTextField1.setText(Name);
        jPasswordField1.setText(Pass);
        jPasswordField2.setText(Pass);
      
        jTextField5.setText(userN);
        jComboBox2.setSelectedItem(staff);
        }
        
        
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
        // TODO add your handling code here:
        tableload();
        
        
        
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void jComboBox3PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox3PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3PopupMenuWillBecomeInvisible

    private void jComboBox3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox3MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3MouseReleased

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox3PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox3PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3PropertyChange

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int x =JOptionPane.showConfirmDialog(null, "Do you really want to close");
       if (x==0) {
            this.dispose();
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int x=JOptionPane.showConfirmDialog(null, "Do you really want to delete this entry");
         
        if(x==0){
            String id=jLabel8.getText();
            String Staff=jComboBox3.getSelectedItem().toString();
            
            if (Staff=="Nurses"){
                
                try {
                String sql="DELETE from Nurses_det where Nur_id='"+id+"' ";
                
                pst=con.prepareStatement(sql);
                pst.execute();
                
                
                tableload();
                   
                JOptionPane.showMessageDialog(null, "Successfully delecte");
                reset();
            } catch (Exception e) {
                
            }
                
                
                
            }
            else if (Staff=="Maintenance staff"){
                
                try {
                String sql="DELETE from MaintenanceStaff_det where Staff_id='"+id+"' ";
                
                pst=con.prepareStatement(sql);
                pst.execute();
                
                
                tableload();
                   
                JOptionPane.showMessageDialog(null, "Successfully delecte");
                reset();
            } catch (Exception e) {
                
            }
                
                
                
            }
            else if (Staff=="Lab assistants"){
                
                try {
                String sql="DELETE from LabAssistants_det where Ass_Id='"+id+"' ";
                
                pst=con.prepareStatement(sql);
                pst.execute();
                
                
                tableload();
                   
                JOptionPane.showMessageDialog(null, "Successfully delecte");
                reset();
            } catch (Exception e) {
                
            }
                
                
                
            }
            else if (Staff=="Register"){
                
                try {
                String sql="DELETE from Register_det where Reg_Id='"+id+"' ";
                
                pst=con.prepareStatement(sql);
                pst.execute();
                
                
                tableload();
                   
                JOptionPane.showMessageDialog(null, "Successfully delecte");
                reset();
            } catch (Exception e) {
                
            }
                
                
                
            }
            
            
            
            
            
        } 
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Add_Staff().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Add_Staff.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

    private String md5(String Pass) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
